# Generated by Django 5.2.6 on 2025-09-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_shift_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('past_7_day_work_hours', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=50, unique=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traffic_level', models.CharField(max_length=50)),
                ('base_time', models.IntegerField(help_text='Base time in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('value_rs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_timestamp', models.DateTimeField(blank=True, null=True)),
                ('assigned_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_api.route')),
            ],
        ),
    ]
