# Generated by Django 5.2.6 on 2025-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0002_order_bonus_order_fuel_cost_order_is_late_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('num_drivers', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('max_hours_per_day', models.IntegerField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('efficiency_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('on_time_deliveries', models.IntegerField()),
                ('late_deliveries', models.IntegerField()),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_orders', models.IntegerField()),
                ('avg_delivery_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('high_value_orders', models.IntegerField(default=0)),
            ],
        ),
    ]
